//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_ban_dien_thoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDatHang
    {
        public int SoDH { get; set; }
        public int MaDT { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> GiaCuoi { get; set; }
        public Nullable<int> Thanhtien { get; set; }
    
        public virtual DienThoai DienThoai { get; set; }
        public virtual DonHang DonHang { get; set; }
    }
}
