//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_ban_dien_thoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaSP
    {
        public int MaDanhGia { get; set; }
        public Nullable<int> MaDT { get; set; }
        public Nullable<int> MaKH { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<int> Rate { get; set; }
    
        public virtual DienThoai DienThoai { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
