//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_ban_dien_thoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DienThoai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DienThoai()
        {
            this.CTDatHangs = new HashSet<CTDatHang>();
            this.DanhGiaSPs = new HashSet<DanhGiaSP>();
        }
    
        public int MaDT { get; set; }
        public string TenDT { get; set; }
        public Nullable<int> GiaGoc { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> GiaCuoi { get; set; }
        public Nullable<double> ManHinh { get; set; }
        public string LoaiManHinh { get; set; }
        public string Chip { get; set; }
        public Nullable<int> Ram { get; set; }
        public Nullable<int> Rom { get; set; }
        public Nullable<int> Cam { get; set; }
        public Nullable<int> CamSau { get; set; }
        public Nullable<int> Pin { get; set; }
        public Nullable<int> MaPL { get; set; }
        public Nullable<System.DateTime> Ngaycapnhat { get; set; }
        public Nullable<int> Soluongban { get; set; }
        public Nullable<int> soluotxem { get; set; }
        public string HinhChiTiet0 { get; set; }
        public string HinhChiTiet1 { get; set; }
        public string HinhChiTiet2 { get; set; }
        public string HinhChiTiet3 { get; set; }
        public string HinhChiTiet4 { get; set; }
        public string HinhChiTiet5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDatHang> CTDatHangs { get; set; }
        public virtual PhanLoai PhanLoai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaSP> DanhGiaSPs { get; set; }
    }
}
