//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_ban_dien_thoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int MaNV { get; set; }
        public Nullable<int> MaVT { get; set; }
        public string HoTenNV { get; set; }
        public string DiachiNV { get; set; }
        public string DienthoaiNV { get; set; }
        public string VaiTro { get; set; }
        public Nullable<bool> Host { get; set; }
        public string TenDN { get; set; }
        public string Matkhau { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public string Gioitinh { get; set; }
        public string Email { get; set; }
        public Nullable<int> Luong { get; set; }
    }
}
