//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_ban_dien_thoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuKien
    {
        public int MaSK { get; set; }
        public string TenSK { get; set; }
        public string Mota { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public string HinhAnh { get; set; }
        public string NoiDungI { get; set; }
        public string NoiDungII { get; set; }
        public string NoiDungIII { get; set; }
    }
}
